stages:
  - build
  - approve-changes
  - deploy

default:
  tags:
    - nix
  before_script:
    - . "$HOME/.nix-profile/etc/profile.d/nix.sh"

prebuild:
  stage: build
  script:
    - nix build .#prebuild

plan:
  stage: approve-changes
  script:
    - nix run .#plan -- -out ./tf.plan
  artifacts:
    paths: [ ./tf.plan ]
    public: false

deploy:
  stage: deploy
  script:
    - nix run .#apply -- ./tf.plan
  environment: production
  rules:
    - when: manual