stages:
  - build
  - approve-changes
  - deploy

default:
  tags:
    - nix
  before_script:
    - . "$HOME/.nix-profile/etc/profile.d/nix.sh"
    # - export NIX_CONFIG=extra-experimental-features='nix-command flakes'

build-job:
  stage: build
  script:
    - nix build . .#nixosConfigurations.gitlab.config.system.build.toplevel

plan:
  stage: approve-changes
  script:
    - nix run .#plan -- -out ./tf.plan

.deploy:
  stage: deploy
  script:
    - nix run .#apply -- ./tf.plan
  environment: production
  rules:
    - when: manual